export interface Quote {
  text: string;
  author: string;
}

const QUOTES: Quote[] = [
  { text: 'Small daily habits lead to massive long-term results.', author: 'Unknown' },
  { text: 'Discipline is the bridge between goals and accomplishment.', author: 'Jim Rohn' },
  { text: 'You do not rise to the level of your goals. You fall to the level of your systems.', author: 'James Clear' },
  { text: 'Motivation gets you going, but discipline keeps you growing.', author: 'John C. Maxwell' },
  { text: 'Success is the sum of small efforts, repeated day in and day out.', author: 'Robert Collier' },
  { text: 'Your future is created by what you do today, not tomorrow.', author: 'Robert Kiyosaki' },
  { text: 'First forget inspiration. Habit is more dependable.', author: 'Octavia Butler' },
  { text: 'Quality is not an act, it is a habit.', author: 'Aristotle' },
  { text: 'Motivation is what gets you started. Habit is what keeps you going.', author: 'Jim Ryun' },
  { text: 'The journey of a thousand miles begins with a single step.', author: 'Lao Tzu' },
  { text: 'Good habits formed at youth make all the difference.', author: 'Aristotle' },
  { text: 'Successful people are simply those with successful habits.', author: 'Brian Tracy' },
  { text: 'Habits change into character.', author: 'Ovid' },
  { text: 'All our life, so far as it has definite form, is but a mass of habits.', author: 'William James' },
  { text: 'We first make our habits, and then our habits make us.', author: 'John Dryden' },
  { text: 'Champions do not become champions when they win the event, but in the hours, weeks, months and years they spend preparing for it.', author: 'T. Alan Armstrong' },
  { text: 'By constant self-discipline and self-control you can develop greatness of character.', author: 'Grenville Kleiser' },
  { text: 'It is not what we do once in a while that shapes our lives, but what we do consistently.', author: 'Tony Robbins' },
  { text: 'A habit cannot be tossed out the window; it must be coaxed down the stairs a step at a time.', author: 'Mark Twain' },
  { text: 'You’ll never change your life until you change something you do daily.', author: 'John C. Maxwell' },
  { text: 'Greatness is not a function of circumstance. Greatness, it turns out, is largely a matter of conscious choice, and discipline.', author: 'Jim Collins' },
  { text: 'The secret of your future is hidden in your daily routine.', author: 'Mike Murdock' },
  { text: 'Habits are the compound interest of self-improvement.', author: 'James Clear' },
  { text: 'Habits are the invisible architecture of daily life.', author: 'Gretchen Rubin' },
  { text: 'Motivation is a fire from within. If someone else tries to light that fire under you, chances are it will burn very briefly.', author: 'Stephen R. Covey' },
  { text: 'The hard days are what make you stronger.', author: 'Aly Raisman' },
  { text: 'Without self-discipline, success is impossible, period.', author: 'Lou Holtz' },
  { text: 'Discipline equals freedom.', author: 'Jocko Willink' },
  { text: 'You are what you do, not what you say you\'ll do.', author: 'Carl Jung' },
  { text: 'What you do today can improve all your tomorrows.', author: 'Ralph Marston' },
  { text: 'I fear not the man who has practiced 10,000 kicks once, but I fear the man who has practiced one kick 10,000 times.', author: 'Bruce Lee' },
  { text: 'Don\'t count the days, make the days count.', author: 'Muhammad Ali' },
  { text: 'If you are going through hell, keep going.', author: 'Winston Churchill' },
  { text: 'Do something today that your future self will thank you for.', author: 'Sean Patrick Flanery' },
  { text: 'Action is the foundational key to all success.', author: 'Pablo Picasso' },
  { text: 'Either you run the day or the day runs you.', author: 'Jim Rohn' },
  { text: 'The best time to plant a tree was 20 years ago. The second best time is now.', author: 'Chinese Proverb' },
  { text: 'A year from now you may wish you had started today.', author: 'Karen Lamb' },
  { text: 'Do not wait for the perfect time and place to enter, for you are already onstage.', author: 'Unknown' },
  { text: 'Everything you\'ve ever wanted is on the other side of fear.', author: 'George Addair' },
  { text: 'Don\'t watch the clock; do what it does. Keep going.', author: 'Sam Levenson' },
  { text: 'There are no shortcuts to any place worth going.', author: 'Beverly Sills' },
  { text: 'Success is walking from failure to failure with no loss of enthusiasm.', author: 'Winston Churchill' },
  { text: 'Believe you can and you\'re halfway there.', author: 'Theodore Roosevelt' },
  { text: 'Start where you are. Use what you have. Do what you can.', author: 'Arthur Ashe' },
  { text: 'Never give up on a dream just because of the time it will take to accomplish it. The time will pass anyway.', author: 'Earl Nightingale' },
  { text: 'Whether you think you can or you think you can\'t, you\'re right.', author: 'Henry Ford' },
  { text: 'Make each day your masterpiece.', author: 'John Wooden' },
  { text: 'I attribute my success to this: I never gave or took any excuse.', author: 'Florence Nightingale' },
  { text: 'What seems to us as bitter trials are often blessings in disguise.', author: 'Oscar Wilde' },
  { text: 'The only place where success comes before work is in the dictionary.', author: 'Vidal Sassoon' },
  { text: 'Character is the ability to carry out a good resolution long after the excitement of the moment has passed.', author: 'Cavett Robert' },
  { text: 'Losers quit when they fail. Winners fail until they succeed.', author: 'Robert T. Kiyosaki' },
  { text: 'I am not a product of my circumstances. I am a product of my decisions.', author: 'Stephen Covey' },
  { text: 'If you continually ask yourself, \'What is important now?\' you won\'t waste time.', author: 'Lou Holtz' },
  { text: 'Our character is basically a composite of our habits.', author: 'Stephen Covey' },
  { text: 'You do not have to be excellent to start, but you have to start to be excellent.', author: 'Zig Ziglar' },
  { text: 'Continuous improvement is better than delayed perfection.', author: 'Mark Twain' },
  { text: 'Do what is right, not what is easy.', author: 'Unknown' },
  { text: 'We are repeatedly what we do. Excellence, then, is not an act, but a habit.', author: 'Will Durant' },
  { text: 'The man who moves a mountain begins by carrying away small stones.', author: 'Confucius' },
  { text: 'To change a habit, make a conscious decision, then act out the new behavior.', author: 'Maxwell Maltz' },
  { text: 'Winning is a habit. Unfortunately, so is losing.', author: 'Vince Lombardi' },
  { text: 'Drop by drop is the water pot filled.', author: 'Buddha' },
  { text: 'We become what we repeatedly do.', author: 'Sean Covey' },
  { text: 'If you pick the right small behavior and sequence it right, you won\'t have to motivate yourself to have it grow.', author: 'BJ Fogg' },
  { text: 'Habits sum up our character.', author: 'BKS Iyengar' },
  { text: 'Your net worth to the world is usually determined by what remains after your bad habits are subtracted from your good ones.', author: 'Benjamin Franklin' },
  { text: 'I can predict the long-term outcome of your success if you show me your daily habits.', author: 'John Maxwell' },
  { text: 'Good habits are worth being fanatical about.', author: 'John Irving' },
  { text: 'Repetition of the same thought or physical action develops into a habit.', author: 'Norman Vincent Peale' },
  { text: 'Routine is a mechanism for survival.', author: 'Unknown' },
  { text: 'It\'s not about perfect. It\'s about effort.', author: 'Jillian Michaels' },
  { text: 'Every action you take is a vote for the type of person you wish to become.', author: 'James Clear' },
  { text: 'Little strokes fell great oaks.', author: 'Benjamin Franklin' },
  { text: 'Sow a thought, and you reap an act; Sow an act, and you reap a habit; Sow a habit, and you reap a character; Sow a character, and you reap a destiny.', author: 'Charles Reade' },
  { text: 'Focus on the journey, not the destination.', author: 'Greg Anderson' },
  { text: 'By failing to prepare, you are preparing to fail.', author: 'Benjamin Franklin' },
  { text: 'Tough times never last, but tough people do.', author: 'Robert H. Schuller' },
  { text: 'The difference between ordinary and extraordinary is that little extra.', author: 'Jimmy Johnson' },
  { text: 'Do not let what you cannot do interfere with what you can do.', author: 'John Wooden' },
  { text: 'I find that the harder I work, the more luck I seem to have.', author: 'Thomas Jefferson' },
  { text: 'Inaction breeds doubt and fear. Action breeds confidence and courage.', author: 'Dale Carnegie' },
  { text: 'We are what we repeatedly do.', author: 'Aristotle' },
  { text: 'It takes 21 days to form a habit.', author: 'Maxwell Maltz' },
  { text: 'Be stronger than your excuses.', author: 'Unknown' },
  { text: 'The only bad workout is the one that didn\'t happen.', author: 'Unknown' },
  { text: 'Energy and persistence conquer all things.', author: 'Benjamin Franklin' },
  { text: 'Strive for progress, not perfection.', author: 'Unknown' },
  { text: 'You may have to fight a battle more than once to win it.', author: 'Margaret Thatcher' },
  { text: 'Out of difficulties grow miracles.', author: 'Jean de la Bruyere' },
  { text: 'The obstacle is the path.', author: 'Zen Proverb' },
  { text: 'If it doesn\'t challenge you, it doesn\'t change you.', author: 'Fred DeVito' },
  { text: 'Fall seven times, stand up eight.', author: 'Japanese Proverb' },
  { text: 'The past does not equal the future.', author: 'Tony Robbins' },
  { text: 'Don\'t stop when you\'re tired. Stop when you\'re done.', author: 'David Goggins' },
  { text: 'No matter how slow you go, you are still lapping everybody on the couch.', author: 'Unknown' },
  { text: 'A little progress every day adds up to big results.', author: 'Unknown' },
  { text: 'Rome wasn\'t built in a day, but they were laying bricks every hour.', author: 'John Heywood' },
  { text: 'Always bear in mind that your own resolution to succeed is more important than any other.', author: 'Abraham Lincoln' },
  { text: 'Habit is either the best of servants or the worst of masters.', author: 'Nathaniel Emmons' },
  { text: 'Good habits are as addictive as bad habits, and a lot more rewarding.', author: 'Harvey Mackay' },
  { text: 'You can\'t just focus on the outcome. You have to focus on the process.', author: 'Unknown' },
  { text: 'The successful warrior is the average man, with laser-like focus.', author: 'Bruce Lee' },
  { text: 'If we don\'t discipline ourselves, the world will do it for us.', author: 'William Feather' },
];

export function getRandomQuote(): Quote {
  if (!QUOTES.length) {
    return { text: 'Stay motivated!', author: 'Habit Tracker' };
  }
  const idx = Math.floor(Math.random() * QUOTES.length);
  const quote = QUOTES[idx];
  if (!quote || !quote.text || !quote.author) {
    return { text: 'Stay motivated!', author: 'Kairos' };
  }
  return quote;
}

